services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franchise
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: franchise-api
    container_name: franchise_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/franchise
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  mysql_data:
