# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "franchise-sam"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "franchise-sam"
region = "us-east-1"
parameter_overrides = "VpcId=\"vpc-0cfe64df8921e784f\" DBPasswordSecret=\"SuperSecretPassword123\" SubnetIds=\"subnet-0bb51001e184e402a,subnet-04acbe64721858e66,subnet-090fc5c2d82b3d202,subnet-0ad276fa3edfa2ad6,subnet-0c3d061e4a573d246,subnet-0409af7b082c76e17\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "franchise-sam"
region = "us-east-1"
parameter_overrides = "VpcId=\"vpc-0cfe64df8921e784f\" DBPasswordSecret=\"SuperSecretPassword123\""
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
