AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  franchise-sam with RDS MySQL

Globals:
  Function:
    Timeout: 3

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID where the RDS instance will be created"
  DBPasswordSecret:
    Type: String
    Description: "Password for the RDS MySQL instance"
    NoEcho: true

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: FranchiseDB
      Engine: mysql
      EngineVersion: '8.0.39'
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      MasterUsername: admin
      MasterUserPassword: !Ref DBPasswordSecret
      DBName: franchise
      MultiAZ: false
      StorageType: gp2
      BackupRetentionPeriod: 7

Outputs:
  RDSInstanceEndpoint:
    Description: "RDS MySQL Instance Endpoint"
    Value: !GetAtt RDSInstance.Endpoint.Address
  RDSDatabaseName:
    Description: "Database Name"
    Value: !Ref RDSInstance
